<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm">
    
    <xacro:property name="arm_len" value="0.1" />
    <xacro:property name="body_len" value="0.2" />

    <xacro:macro name="arm" params="side up_or_low f_or_b offset">
        <link name="${f_or_b}_${side}_${up_or_low}_arm">
            <visual>
                <geometry>
                    <box size="${arm_len} ${arm_len / 4} ${arm_len / 4}"/>
                </geometry>
                <origin xyz="${offset}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${arm_len} ${arm_len / 4} ${arm_len / 4}"/>
                </geometry>
                <origin xyz="${offset}"/>
            </collision>
        </link>
    </xacro:macro> 

    <xacro:macro name="limb" params="side f_or_b offset">
        <joint name="${f_or_b}_${side}_shoulder" type="revolute">
                <parent link="base_link"/>
                <child link="${f_or_b}_${side}_upper_arm"/>
                <limit lower="-.8" upper=".8" effort="0.0" velocity="0.0"/>
                <origin xyz = ".05 ${offset * (.05)} 0"/>
                <axis xyz="0 0 1"/>
            </joint>

        <joint name="${f_or_b}_${side}_elbow_joint" type="revolute">
            <parent link="${f_or_b}_${side}_upper_arm"/>
            <child link="${f_or_b}_${side}_lower_arm"/>
            <limit lower="1.1" upper="1.2" effort="0.0" velocity="0.0"/>
            <origin xyz = "0.1 0 0"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_len} ${body_len/2} .01"/>
            </geometry>
            <origin rpy="0 0 ${3.14/2}"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_len} ${body_len/2} .01"/>
            </geometry>
            <origin rpy="0 0 ${3.14/2}"/>
        </collision>
    </link>
    
    <xacro:arm side="right" up_or_low="lower" f_or_b="front" offset=".05 0 0" />

    <xacro:arm side="right" up_or_low="upper" f_or_b="front" offset=".05 0 0"/>

    <xacro:limb side="right" f_or_b="front" offset="1"/>
    
    <xacro:arm side="right" up_or_low="lower" f_or_b="back" offset=".05 0 0" />

    <xacro:arm side="right" up_or_low="upper" f_or_b="back" offset=".05 0 0"/>

    <xacro:limb side="right" f_or_b="back" offset="-1"/>

</robot>