<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm">

<xacro:property name="total_mass" value="70" /> <!--KG-->
<xacro:property name="height" value="1.75" /> <!--METERS-->

<!--Height Proportions-->
<xacro:property name="head_len" value="${height*0.13}" />
<xacro:property name="neck_len" value="${height*0.04}" />
<xacro:property name="torso_len" value="${height*0.29}" />
<xacro:property name="upper_arm_len" value="${height*0.19}" />
<xacro:property name="forearm_len" value="${height*0.15}" />
<xacro:property name="hand_len" value="${height*0.11}" />
<xacro:property name="thigh_len" value="${height*0.24}" />
<xacro:property name="calf_len" value="${height*0.22}" />
<xacro:property name="foot_len" value="${height*0.07}" />

<!--Limb Thickness-->
<xacro:property name="upper_arm_thickness" value="${upper_arm_len*0.09}" />
<xacro:property name="forearm_thickness" value="${forearm_len*0.08}" />
<xacro:property name="thigh_thickness" value="${thigh_len*0.14}" />
<xacro:property name="calf_thickness" value="${calf_len*0.095}" />
<xacro:property name="torso_thickness" value="${torso_len*0.20}" />
<xacro:property name="neck_thickness" value="${neck_len*0.045}" />
<xacro:property name="foot_thickness" value="${foot_len*0.045}" />

<xacro:macro name="limb" params="name length offset rpy width">
    <link name="${name}">
        <visual>
            <geometry>
                <cylinder radius="${width}" length="${length}"/>
            </geometry>
            <origin xyz="${offset}" rpy="${rpy}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${width}" length="${length}"/>
            </geometry>
            <origin xyz="${offset}" rpy="${rpy}"/>
        </collision>
    </link>
</xacro:macro>

<xacro:macro name="affix" params="name parent child">
    <joint name="${name}" type="fixed">
        <parent link="${parent}"/>
        <child link="${child}"/>
    </joint>
</xacro:macro>

<xacro:macro name="revolve" params="name parent child hi lo axis offset">
    <joint name="${name}" type="revolute">
        <parent link="${parent}"/>
        <child link="${child}"/>
        <limit lower="${lo}" upper="${hi}" effort="20.0" velocity="20.0"/>
        <origin xyz="${offset}"/>
        <axis xyz="${axis}"/>
    </joint>
</xacro:macro>



<!--LIMBS-->
<xacro:limb name="neck" length="${neck_len}" offset="0 0 ${torso_len}" rpy="0 0 0" width="${neck_thickness}"/>

<xacro:limb name="torso" length="${torso_len}" offset="0 0 0" rpy="0 0 0" width="${torso_thickness}"/>

<xacro:limb name="right_thigh" length="${thigh_len}" offset="0 0 -${thigh_len*.5}" rpy="0 0 0" width="${thigh_thickness}"/>
<xacro:limb name="left_thigh" length="${thigh_len}" offset="0 0 -${thigh_len*.5}" rpy="0 0 0" width="${thigh_thickness}"/>

<xacro:limb name="right_calf" length="${calf_len}" offset="0 0 -${calf_len*.5}" rpy="0 0 0" width="${calf_thickness}"/>
<xacro:limb name="left_calf" length="${calf_len}" offset="0 0 -${calf_len*.5}" rpy="0 0 0" width="${calf_thickness}"/>

<link name="right_foot">
    <visual>
        <geometry>
            <box size="${calf_thickness*1.5} ${foot_len} ${calf_thickness}"/>
        </geometry>
        <origin xyz="0 ${foot_len * .25} -${calf_thickness * .5}"/>
    </visual>
    <collision>
        <geometry>
            <box size="${calf_thickness*1.5} ${foot_len} ${calf_thickness}"/>
        </geometry>
        <origin xyz="0 ${foot_len * .25} -${calf_thickness * .5}"/>
    </collision>
</link>

<link name="left_foot">
    <visual>
        <geometry>
            <box size="${calf_thickness*1.5} ${foot_len} ${calf_thickness}"/>
        </geometry>
        <origin xyz="0 ${foot_len * .25} -${calf_thickness * .5}"/>
    </visual>
    <collision>
        <geometry>
            <box size="${calf_thickness*1.5} ${foot_len} ${calf_thickness}"/>
        </geometry>
        <origin xyz="0 ${foot_len * .25} -${calf_thickness * .5}"/>
    </collision>
</link>

<xacro:affix name="vertibre" parent="torso" child="neck"/>

<!--REV JOINTS-->
<xacro:revolve name="right_hip_flexor" parent="torso" child="right_thigh" lo="-1.2" hi="1.2"
axis="1 0 0" offset="${torso_thickness*.5} 0 -${torso_len*.5}"/>
<xacro:revolve name="left_hip_flexor" parent="torso" child="left_thigh" lo="-1.2" hi="1.2"
axis="1 0 0" offset="-${torso_thickness*.5} 0 -${torso_len*.5}"/>

<xacro:revolve name="right_knee" parent="right_thigh" child="right_calf" lo="-1.2" hi="0"
axis="1 0 0" offset="0 0 -${thigh_len}"/>
<xacro:revolve name="left_knee" parent="left_thigh" child="left_calf" lo="-1.2" hi="0"
axis="1 0 0" offset="0 0 -${thigh_len}"/>

<xacro:revolve name="right_ankle" parent="right_calf" child="right_foot" lo="-1.2" hi="1.2"
axis="1 0 0" offset="0 0 -${calf_len}"/>
<xacro:revolve name="left_ankle" parent="left_calf" child="left_foot" lo="-1.2" hi="1.2"
axis="1 0 0" offset="0 0 -${calf_len}"/>


</robot>
