<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm">
    
    <xacro:property name="leg_len" value="0.1" />
    <xacro:property name="body_len" value="0.2" />

    <material name = "red">
        <color rgba=".8 0 0 1"/>
    </material>

    <material name = "clear">
        <color rgba="1 1 1 .5"/>
    </material>

    <xacro:macro name="limb" params="name side offset rpy">
        <link name="${side}_${name}">
            <visual>
                <geometry>
                    <box size="${leg_len/8} ${leg_len/8} ${leg_len/2}"/>
                </geometry>
                <origin xyz="${offset}" rpy="${rpy}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${leg_len/8} ${leg_len/8} ${leg_len/2}"/>
                </geometry>
                <origin xyz="${offset}"/>
            </collision>
        </link>
    </xacro:macro> 

    <xacro:macro name="connection" params="name limb1 limb2 lo hi offset">
        <joint name="${name}" type="revolute">
            <parent link="${limb1}"/>
            <child link="${limb2}"/>
            <limit lower="${lo}" upper="${hi}" effort="0.0" velocity="0.0"/>
            <origin xyz="${offset}"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="0.6" radius="0.2"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 .8 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.6" radius="0.2"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="10"/>
            <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
        </inertial>
  </link>

</robot>